# -*- coding: utf-8 -*-
"""Easy_10_CP_Practical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftZz1Veg0Z8v_bbEYYHsmLX3rEceQ_rh
"""

import numpy as np
import matplotlib.pyplot as plt
from numba import cuda
import time
import math

# STEP 1: Generate Dataset
N = 10_000_000

np.random.seed(42)

# Highest CUDA-supported precision = float64
dataset = np.random.uniform(
    low=0.0,
    high=1e12,
    size=N
).astype(np.float64)

print("=" * 60)
print("DATASET GENERATED")
print("=" * 60)

print("Dataset Size :", len(dataset))
print("Datatype     :", dataset.dtype)

print("\nFirst 10 Values:")
for value in dataset[:10]:
    print(f"{value:.15f}")

# STEP 2: CUDA Kernel
# Count values whose integer part is odd


@cuda.jit
def count_odd_integer_part_kernel(arr, odd_count):

    idx = cuda.grid(1)

    if idx < arr.size:

        integer_part = int(arr[idx])

        if integer_part % 2 == 1:
            cuda.atomic.add(odd_count, 0, 1)

# STEP 3: CUDA Execution Function


def count_odds_cuda(data):

    d_arr = cuda.to_device(data)

    odd_count = np.zeros(1, dtype=np.int64)

    d_odd_count = cuda.to_device(odd_count)

    threads_per_block = 256
    blocks_per_grid = math.ceil(
        len(data) / threads_per_block
    )

    start = time.time()

    count_odd_integer_part_kernel[
        blocks_per_grid,
        threads_per_block
    ](
        d_arr,
        d_odd_count
    )

    cuda.synchronize()

    gpu_time = time.time() - start

    result = d_odd_count.copy_to_host()[0]

    return result, gpu_time

# STEP 4: Execute On Small Sample


sample_data = dataset[:100]

sample_count, sample_time = count_odds_cuda(sample_data)

print("\n" + "=" * 60)
print("SAMPLE EXECUTION")
print("=" * 60)

print("Sample Size              :", len(sample_data))
print("Odd Integer Part Count   :", sample_count)
print("Execution Time (sec)     :", round(sample_time, 6))

# STEP 5: Execute On Full Dataset

gpu_odd_count, gpu_time = count_odds_cuda(dataset)

gpu_even_count = len(dataset) - gpu_odd_count

print("\n" + "=" * 60)
print("CUDA RESULTS")
print("=" * 60)

print("Total Records            :", len(dataset))
print("Odd Integer Part Count   :", gpu_odd_count)
print("Even Integer Part Count  :", gpu_even_count)
print("CUDA Time (sec)          :", round(gpu_time, 4))

# STEP 6: CPU Verification


cpu_start = time.time()

cpu_odd_count = np.sum(
    dataset.astype(np.int64) % 2 == 1
)

cpu_time = time.time() - cpu_start

print("\n" + "=" * 60)
print("CPU VERIFICATION")
print("=" * 60)

print("CPU Odd Count            :", cpu_odd_count)
print("CPU Time (sec)           :", round(cpu_time, 4))

if cpu_odd_count == gpu_odd_count:
    print("Verification             : PASSED")
else:
    print("Verification             : FAILED")


# STEP 7: PRE-OPERATION VISUALIZATION
# Distribution of Floating Point Values


plt.figure(figsize=(12, 6))

plt.hist(
    dataset[:100000],
    bins=100
)

plt.title(
    "Pre-Operation: Distribution of 100K Double Precision Values"
)

plt.xlabel("Value")
plt.ylabel("Frequency")
plt.grid(True)

plt.show()


# STEP 8: PRE-OPERATION SCATTER PLOT


plt.figure(figsize=(12, 6))

plt.scatter(
    np.arange(2000),
    dataset[:2000],
    s=5
)

plt.title(
    "Pre-Operation: First 2000 Double Precision Values"
)

plt.xlabel("Index")
plt.ylabel("Value")
plt.grid(True)

plt.show()


# STEP 9: POST-OPERATION VISUALIZATION
# Odd vs Even Integer Parts


labels = [
    "Odd Integer Part",
    "Even Integer Part"
]

counts = [
    gpu_odd_count,
    gpu_even_count
]

plt.figure(figsize=(8, 6))

bars = plt.bar(
    labels,
    counts
)

plt.title(
    "Post-Operation: Odd vs Even Integer Parts"
)

plt.ylabel("Count")

for bar in bars:

    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f"{int(height):,}",
        ha='center'
    )

plt.show()


# STEP 10: PIE CHART


odd_percentage = (
    gpu_odd_count / len(dataset)
) * 100

even_percentage = (
    gpu_even_count / len(dataset)
) * 100

plt.figure(figsize=(8, 8))

plt.pie(
    [odd_percentage, even_percentage],
    labels=["Odd", "Even"],
    autopct="%1.2f%%"
)

plt.title(
    "Percentage Distribution of Odd/Even Integer Parts"
)

plt.show()

# STEP 11: PRECISION CHECK

print("\n" + "=" * 60)
print("DOUBLE PRECISION CHECK")
print("=" * 60)

for i in range(5):
    print(
        f"Value {i+1}: "
        f"{dataset[i]:.15f}"
    )

# STEP 12: STATISTICS REPORT

print("\n" + "=" * 60)
print("DATASET STATISTICS")
print("=" * 60)

print(f"Dataset Size          : {len(dataset):,}")
print(f"Datatype              : {dataset.dtype}")

print(f"Minimum Value         : {dataset.min():.15f}")
print(f"Maximum Value         : {dataset.max():.15f}")

print(f"Mean Value            : {dataset.mean():.15f}")
print(f"Median Value          : {np.median(dataset):.15f}")

print(f"Standard Deviation    : {dataset.std():.15f}")

print("\nOdd/Even Statistics")

print(f"Odd Integer Parts     : {gpu_odd_count:,}")
print(f"Even Integer Parts    : {gpu_even_count:,}")

print(f"Odd Percentage        : {odd_percentage:.4f}%")
print(f"Even Percentage       : {even_percentage:.4f}%")

print("\nPerformance")

print(f"CUDA Execution Time   : {gpu_time:.4f} sec")
print(f"CPU Execution Time    : {cpu_time:.4f} sec")

if gpu_time > 0:
    print(
        f"GPU Speedup           : "
        f"{cpu_time / gpu_time:.2f}x"
    )